import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#faf8ff',
          dim: '#d9d9e5',
          bright: '#faf8ff',
          lowest: '#ffffff',
          low: '#f3f2fe',
          container: '#ededf9',
          'container-high': '#e8e7f3',
          'container-highest': '#e2e1ed',
          variant: '#e2e1ed',
          card: '#FFFFFF',
          background: '#F9FAFB',
        },
        onSurface: {
          DEFAULT: '#1a1b23',
          variant: '#434655',
        },
        inverse: {
          surface: '#2e3039',
          onSurface: '#f0f0fb',
          primary: '#b7c4ff',
        },
        surfaceTint: '#2151da',
        primary: {
          DEFAULT: '#0037b0',
          container: '#1d4ed8',
          onContainer: '#cad3ff',
          fixed: '#dce1ff',
          'fixed-dim': '#b7c4ff',
          onFixed: '#001551',
          'onFixed-variant': '#0039b5',
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        onPrimary: '#ffffff',
        secondary: {
          DEFAULT: '#006c49',
          container: '#6cf8bb',
          onContainer: '#00714d',
          fixed: '#6ffbbe',
          'fixed-dim': '#4edea3',
          onFixed: '#002113',
          'onFixed-variant': '#005236',
        },
        onSecondary: '#ffffff',
        tertiary: {
          DEFAULT: '#7f2500',
          container: '#a73400',
          onContainer: '#ffc9b7',
          fixed: '#ffdbcf',
          'fixed-dim': '#ffb59c',
          onFixed: '#390c00',
          'onFixed-variant': '#832700',
        },
        onTertiary: '#ffffff',
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
          onContainer: '#93000a',
        },
        onError: '#ffffff',
        background: '#faf8ff',
        onBackground: '#1a1b23',
        outline: '#747686',
        'outline-variant': '#c4c5d7',
        border: {
          subtle: '#E5E7EB',
        },
        text: {
          primary: '#111827',
          secondary: '#6B7280',
        },
        chart: {
          blue: '#3B82F6',
          green: '#10B981',
          amber: '#F59E0B',
          red: '#EF4444',
        },
      },
      fontFamily: {
        display: ['Inter'],
        h1: ['Inter'],
        h2: ['Inter'],
        body: ['Inter'],
        statValue: ['Inter'],
        labelSm: ['Inter'],
      },
      fontSize: {
        display: ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        h1: ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        h2: ['18px', { lineHeight: '28px', fontWeight: '600' }],
        body: ['14px', { lineHeight: '20px', fontWeight: '400' }],
        statValue: ['24px', { lineHeight: '32px', fontWeight: '700' }],
        labelSm: ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        containerMax: '80rem',
        gutter: '1.5rem',
        sectionGap: '2rem',
        cardPadding: '1.5rem',
        stackSm: '0.5rem',
        stackMd: '1rem',
      },
    },
  },
  plugins: [],
};

export default config;